# Generated by Django 2.1.3 on 2020-03-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('sender', models.CharField(max_length=250)),
                ('receiver', models.CharField(max_length=250)),
                ('chat', models.CharField(max_length=1048576)),
                ('auto', models.AutoField(primary_key=True, serialize=False)),
                ('notification', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('auto', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250)),
                ('chat', models.CharField(max_length=1099511627776)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('username', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('image_file', models.ImageField(null=True, upload_to='images/', verbose_name='')),
                ('auto', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(max_length=1048576)),
                ('BAN', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('phone', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=1000)),
                ('business', models.CharField(max_length=250)),
                ('bio', models.CharField(max_length=2000)),
                ('password', models.CharField(max_length=250)),
                ('pic', models.ImageField(null=True, upload_to='images/', verbose_name='')),
                ('BAN', models.CharField(max_length=250)),
                ('chat', models.CharField(max_length=1099511627776)),
            ],
        ),
    ]
